Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#27 test: add codespell github action
  .github/workflows/codespell.yml
  pkg/util/util.go
Labels: approved, cncf-cla: yes, size/S

#29 test: add codeql-analysis github action
  .github/workflows/codeql-analysis.yml
  .github/workflows/codespell.yml
  .travis.yml
Labels: approved, cncf-cla: yes, size/M

#25 Install Lustre client packages using apt install
  Makefile
  deploy/example/azurelustre/storageclass.yaml
  pkg/azurelustreplugin/Dockerfile
  pkg/azurelustreplugin/entrypoint.sh
  test/integration_aks/image/run_integration_test.sh
Labels: kind/feature, cncf-cla: yes, size/M

#31 [test] add reclaim policy test
  test/external-e2e/run.sh
  test/external-e2e/test_claim.yaml
Labels: cncf-cla: yes, size/M

#32 [fix] fix log level argument
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
Labels: kind/bug, size/XS, cncf-cla: yes

#36 [fix] add copyright info
  hack/boilerplate/boilerplate.py
  hack/verify-integration-test-aks.sh
  pkg/azurelustreplugin/entrypoint.sh
  test/integration_aks/image/Dockerfile
  test/integration_aks/image/run_integration_test.sh
  test/ior/Dockerfile
  test/ior/setup.sh
  test/ior/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/documentation

#34 Fix mgs-ip-address and other minor hard-code changes
  .github/workflows/long_haul.yaml
  Makefile
  README.md
  deploy/example/azurelustre/storageclass.yaml
  docs/examples/pv.yaml
  docs/examples/storageclass_existing_lustre.yaml
  docs/install_csi_driver.md
  pkg/azurelustre/controllerserver.go
  pkg/azurelustre/controllerserver_test.go
  pkg/azurelustre/nodeserver.go
  pkg/azurelustre/nodeserver_test.go
  test/external-e2e/e2etest_storageclass.yaml
  test/integration_aks/image/run_integration_test.sh
  test/ior/Dockerfile
  test/ior/pod.yaml
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/M

#33 Install CSI images from MCR
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
Labels: kind/api-change, cncf-cla: yes, do-not-merge/work-in-progress, size/S

#38 Clone IOR repo with tag 3.3.0
  test/ior/Dockerfile
Labels: kind/api-change, approved, size/XS, cncf-cla: yes, lgtm

#30 [Doc] Modify documentation and add troubleshooting guidance
  README.md
  docs/README.md
  docs/csi-debug.md
  docs/csi-dev.md
  docs/install_csi_driver.md
  docs/static_provisioning.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/documentation

#39 Release v0.1.1, Pull image from MCR and documentation update
  README.md
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
  deploy/example/azurelustre/storageclass.yaml
  deploy/install-driver.sh
  docs/csi-dev.md
  docs/examples/pv.yaml
  docs/examples/pvc_pv.yaml
  docs/examples/pvc_storageclass.yaml
  docs/examples/storageclass_existing_lustre.yaml
  docs/install-csi-driver.md
  docs/static-provisioning.md
  test/external-e2e/e2etest_storageclass.yaml
Labels: kind/api-change, approved, cncf-cla: yes, lgtm, kind/documentation, size/M

#28 [Test] Add draft long-haul test cases
  .github/workflows/long_haul.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/external-e2e/run.sh
  test/long-haul/fault-test.sh
  test/long-haul/sample-workload/deployment_write_print_file.yaml
  test/long-haul/start-long-haul.sh
  test/long-haul/update-test.sh
  test/long-haul/utils.sh
  utils/azurelustre_log.sh
  utils/check_driver_pods_restart.sh
Labels: cncf-cla: yes, lgtm, size/XL

#37 [chore] disable the unused metrics server
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
  go.mod
  pkg/azurelustreplugin/main.go
Labels: kind/cleanup, cncf-cla: yes, lgtm, size/M

#35 [fix] add mount umount lock to fix crash problem
  pkg/azurelustre/azurelustre.go
  pkg/azurelustre/nodeserver.go
Labels: kind/bug, size/XS, cncf-cla: yes

#41 [feat] add mount options support
  pkg/azurelustre/nodeserver.go
  pkg/azurelustre/nodeserver_test.go
Labels: kind/feature, cncf-cla: yes, size/M

#43 [fix] add no-mtab flag to mount
  pkg/azurelustre/nodeserver.go
Labels: size/XS, cncf-cla: yes

#42 [test] Add node metrics and scale test script
  pkg/azurelustre/controllerserver.go
  pkg/azurelustre/nodeserver.go
  test/scale/.gitignore
  test/scale/analysis_log.py
  test/scale/run_test_workload.sh
  test/scale/scale_test_dynamic.yaml
  test/scale/scale_test_static.yaml
Labels: cncf-cla: yes, size/XL
