Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#67 [fix] fix the errors of external e2e test
  test/external-e2e/run.sh
  test/long-haul/external-e2e.sh
  test/long-haul/start-long-haul.sh
Labels: kind/bug, cncf-cla: yes, lgtm, size/S

#69 [test] Updateing external E2E test version
  test/external-e2e/.gitignore
  test/external-e2e/e2etest_storageclass.yaml
  test/external-e2e/e2etest_storageclass.yaml.template
  test/external-e2e/run.sh
  test/long-haul/external-e2e.sh
Labels: cncf-cla: yes, size/M

#70 Modify 'update test case'
  test/long-haul/update-test.sh
Labels: size/XS, cncf-cla: yes
