Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#72 Support Ubuntu 22.04
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
  deploy/example/echodate/storageclass.yaml
  pkg/azurelustreplugin/Dockerfile
  pkg/azurelustreplugin/entrypoint.sh
Labels: kind/feature, cncf-cla: yes, size/M

#76 Add vinli-cn as Owner
  OWNERS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#75 [test] Let perf/scale test installs local CSI driver.
  test/scale/run_test.py
Labels: size/XS, cncf-cla: yes

#77 Update document for v0.1.4
  README.md
Labels: approved, cncf-cla: yes, kind/documentation

#78 [test] fix csi local installation path
  deploy/install-driver.sh
  test/external-e2e/run.sh
Labels: size/XS, cncf-cla: yes

#79 [test] change parameters to supplsupport go 2.0
  test/external-e2e/run.sh
  test/long-haul/external-e2e.sh
Labels: cncf-cla: yes, size/S

#80 [test] fix go lint
  .github/workflows/static.yaml
Labels: size/XS, cncf-cla: yes
