Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#59 Support Lustre 2.15.1
  pkg/azurelustreplugin/entrypoint.sh
Labels: cncf-cla: yes, size/S

#61 Use Release 0.1.3 CSI Image
  README.md
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
Labels: size/XS, cncf-cla: yes

#55 [Test] Improve fault and update test
  deploy/install-driver.sh
  test/long-haul/fault-test.sh
  test/long-haul/sample-workload/deployment_write_print_file.yaml
  test/long-haul/start-long-haul.sh
  test/long-haul/update-test.sh
  test/long-haul/utils.sh
Labels: cncf-cla: yes, size/L

#58 [test] Automated perf scale testing
  test/long-haul/perf-scale-test.sh
  test/long-haul/start-long-haul.sh
  test/scale/.gitignore
  test/scale/analysis_log.py
  test/scale/run_test.py
  test/scale/run_test_workload.sh
  test/scale/scale_test_dynamic.yaml
  test/scale/static_workload.yml.template
Labels: cncf-cla: yes, size/XL

#63 Grant execute permission for long-haul test
  test/long-haul/start-long-haul.sh
  test/long-haul/update-test.sh
  test/long-haul/utils.sh
Labels: size/XS, cncf-cla: yes

#65 fix CVE-2022-32149
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL
