Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#142 Changes to entrypoint for better resilience
  pkg/azurelustreplugin/entrypoint.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#143 Fix flaky test
  pkg/azurelustre/controllerserver_test.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#146 Upgrade kubernetes dependency to avoid CVE
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#145 Bump to 2.15.1-33-g0168b83
  pkg/azurelustreplugin/entrypoint.sh
  test/integration_aks/image/run_integration_test.sh
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm

#147 Minor go fix and CSI version bump to 0.1.12
  Makefile
  pkg/azurelustreplugin/main.go
Labels: kind/cleanup, approved, size/XS, cncf-cla: yes, lgtm

#148 Updating deployment files to new CSI image
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm

#150 Add correct control-plane toleration value
  deploy/csi-azurelustre-controller.yaml
Labels: approved, size/XS, cncf-cla: yes, lgtm
