Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#169 Fix longhaul tests when running on fresh cluster
  test/long-haul/utils.sh
  test/scale/run_test.py
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#171 Correct and update workflows so we can enable Actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/codespell.yml
  .github/workflows/darwin.yaml
  .github/workflows/external_e2e.yaml
  .github/workflows/integration_test_aks.yaml
  .github/workflows/linux.yaml
  .github/workflows/sanity_test_local.yaml
  .github/workflows/static.yaml
  .github/workflows/trivy.yaml
  .github/workflows/windows.yaml
  go.mod
  go.sum
  pkg/csi-common/controllerserver-default.go
Labels: approved, cncf-cla: yes, size/L

#172 Fix minor workflow issues
  .github/workflows/codeql-analysis.yml
  .github/workflows/linux.yaml
  go.sum
  hack/verify-golint.sh
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, size/S

#173 Fix minor workflow issues
  .github/workflows/codeql-analysis.yml
  .github/workflows/linux.yaml
  go.sum
  hack/verify-golint.sh
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, size/S
