Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#185 Add skip for interfaces in unknown state to entrypoint script
  pkg/azurelustreplugin/entrypoint.sh
Labels: kind/bug, approved, size/XS, cncf-cla: yes, lgtm

#187 Bump image to v0.1.16
  Makefile
  README.md
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm

#189 Fix testing
  pkg/azurelustre/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 Upgrade jwt
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 Use force unmount and explicitly unmount bad mount points
  pkg/azurelustre/azurelustre.go
  pkg/azurelustre/fake_mount.go
  pkg/azurelustre/nodeserver.go
  pkg/azurelustre/nodeserver_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/M
