Repository kubernetes-sigs/azurelustre-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#218 Fix race condition in tests
  test/external-e2e/e2etest_storageclass.yaml.template
  test/external-e2e/run.sh
  test/external-e2e/testdriver-azurelustre.yaml
  test/long-haul/sample-workload/deployment_write_print_file.yaml
  test/long-haul/start-long-haul.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#219 Update Go deps
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL

#217 Bump to v0.2.0 image
  README.md
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
  docs/csi-debug.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#220 Releasing from v0.2.0 Development
  Makefile
  README.md
  deploy/csi-azurelustre-controller.yaml
  deploy/csi-azurelustre-node.yaml
  docs/csi-debug.md
  go.mod
  go.sum
  pkg/azurelustreplugin/Dockerfile
  pkg/azurelustreplugin/entrypoint.sh
  test/external-e2e/e2etest_storageclass.yaml.template
  test/external-e2e/run.sh
  test/external-e2e/testdriver-azurelustre.yaml
  test/integration_dalec/integration_dalec_aks.yaml.template
  test/integration_dalec/run_integration_test.sh
  test/integration_dalec/setup_integration_test_dalec.sh
  test/long-haul/sample-workload/deployment_write_print_file.yaml
  test/long-haul/start-long-haul.sh
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL

#221 Pin csc for dalec integration tests
  test/integration_dalec/run_integration_test.sh
Labels: kind/feature, approved, size/XS, cncf-cla: yes, lgtm
